import Foundation
import OSLog

/// One subtitle track advertised by YouTube's player response.
struct CaptionTrack: Identifiable, Hashable, Sendable {
    let id: String
    let languageCode: String
    let name: String
    let url: URL
    let isAutoGenerated: Bool

    var displayName: String {
        isAutoGenerated ? String(localized: "\(name) (auto-generated)") : name
    }
}

/// A timed caption line.
struct CaptionCue: Sendable, Hashable {
    let start: TimeInterval
    let end: TimeInterval
    let text: String
}

/// Caption tracks and cues.
///
/// YouTube's HLS manifests carry no legible tracks, so subtitles come from the player response's
/// `captionTracks` list and the `timedtext` URL behind each one. Since 2025 the URLs handed to
/// the WEB client answer with an *empty 200* unless a proof-of-origin token is attached; the
/// `IOS` client's URLs still serve full transcripts (verified 2026-09-17), so that is the client
/// used here. No cookies are sent — captions are public and the request must not carry the
/// account.
protocol CaptionServicing: Sendable {
    func tracks(videoID: String) async throws -> [CaptionTrack]
    func cues(for track: CaptionTrack) async throws -> [CaptionCue]
}

final class CaptionService: CaptionServicing, @unchecked Sendable {
    private let session: URLSession
    private let log = AppLog(subsystem: "com.leshko.freetube", category: "CaptionService")

    private static let userAgent = "com.google.ios.youtube/21.13.6 (iPhone16,2; U; CPU iOS 26_4 like Mac OS X;)"

    init() {
        let config = URLSessionConfiguration.ephemeral
        config.httpShouldSetCookies = false
        config.httpCookieAcceptPolicy = .never
        config.timeoutIntervalForRequest = 20
        session = URLSession(configuration: config)
    }

    func tracks(videoID: String) async throws -> [CaptionTrack] {
        let body: [String: Any] = [
            "context": [
                "client": [
                    "clientName": "IOS",
                    "clientVersion": "21.13.6",
                    "deviceMake": "Apple",
                    "deviceModel": "iPhone16,2",
                    "osName": "iPhone",
                    "osVersion": "26.4.0.23E240",
                    "hl": Locale.current.language.languageCode?.identifier ?? "en"
                ]
            ],
            "videoId": videoID,
            "contentCheckOk": true,
            "racyCheckOk": true
        ]
        var request = URLRequest(url: URL(string: "https://www.youtube.com/youtubei/v1/player?prettyPrint=false")!)
        request.httpMethod = "POST"
        request.httpBody = try JSONSerialization.data(withJSONObject: body)
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(Self.userAgent, forHTTPHeaderField: "User-Agent")
        let (data, response) = try await session.data(for: request)
        guard let http = response as? HTTPURLResponse, (200..<300).contains(http.statusCode) else {
            throw YouTubeServiceError.network(NSError(domain: "CaptionService", code: (response as? HTTPURLResponse)?.statusCode ?? -1))
        }
        let root = JSONNode(try JSONSerialization.jsonObject(with: data))
        let tracks = root["captions"]["playerCaptionsTracklistRenderer"]["captionTracks"].array.compactMap { node -> CaptionTrack? in
            guard let base = node["baseUrl"].string, let url = URL(string: base),
                  let code = node["languageCode"].string else { return nil }
            let name = node["name"]["simpleText"].string ?? node["name"].runsText ?? code
            let auto = node["kind"].string == "asr"
            return CaptionTrack(id: "\(code):\(auto ? "asr" : "src")", languageCode: code, name: name, url: url, isAutoGenerated: auto)
        }
        log.info("[captions] \(videoID, privacy: .public) → \(tracks.count, privacy: .public) tracks")
        return tracks
    }

    func cues(for track: CaptionTrack) async throws -> [CaptionCue] {
        var components = URLComponents(url: track.url, resolvingAgainstBaseURL: false)
        var items = components?.queryItems ?? []
        items.removeAll { $0.name == "fmt" }
        items.append(URLQueryItem(name: "fmt", value: "json3"))
        components?.queryItems = items
        let url = components?.url ?? track.url

        var request = URLRequest(url: url)
        request.setValue(Self.userAgent, forHTTPHeaderField: "User-Agent")
        let (data, response) = try await session.data(for: request)
        guard let http = response as? HTTPURLResponse, (200..<300).contains(http.statusCode) else {
            throw YouTubeServiceError.network(NSError(domain: "CaptionService", code: (response as? HTTPURLResponse)?.statusCode ?? -1))
        }
        let cues = Self.parseJSON3(data)
        log.info("[captions] \(track.languageCode, privacy: .public) → \(cues.count, privacy: .public) cues")
        return cues
    }

    /// `fmt=json3`: `events[] { tStartMs, dDurationMs, segs[] { utf8 } }`. Events without text
    /// (window definitions) are skipped; consecutive events keep YouTube's own timing.
    static func parseJSON3(_ data: Data) -> [CaptionCue] {
        guard let object = try? JSONSerialization.jsonObject(with: data) else { return [] }
        let root = JSONNode(object)
        var cues: [CaptionCue] = []
        for event in root["events"].array {
            guard let startMs = event["tStartMs"].double else { continue }
            let text = event["segs"].array.compactMap { $0["utf8"].string }.joined()
                .replacingOccurrences(of: "\n", with: " ")
                .trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { continue }
            let durationMs = event["dDurationMs"].double ?? 0
            cues.append(CaptionCue(start: startMs / 1000, end: (startMs + max(durationMs, 500)) / 1000, text: text))
        }
        return cues.sorted { $0.start < $1.start }
    }
}
