import Foundation

/// Subtitle handling. Tracks are fetched once per video after playback is ready (one player
/// request); cues only when a track is selected. The chosen language is remembered and applied to
/// later videos that offer it, so captions behave like a setting rather than a per-video chore.
@available(iOS 17.0, *)
extension PlayerStateManager {
    var hasCaptionTracks: Bool { !captionTracks.isEmpty }

    /// Turns captions on for `track`, or off with `nil`. Persists the language choice.
    func selectCaption(_ track: CaptionTrack?) {
        captionTask?.cancel()
        selectedCaptionTrack = track
        captionCues = []
        currentCaptionText = nil
        preferences.captionLanguageCode = track?.languageCode ?? ""
        guard let track else { return }
        let videoID = currentVideo?.id
        captionTask = Task { [weak self] in
            guard let self else { return }
            do {
                let cues = try await self.captionService.cues(for: track)
                guard !Task.isCancelled, self.currentVideo?.id == videoID, self.selectedCaptionTrack?.id == track.id else { return }
                self.captionCues = cues
                self.updateCurrentCaption()
            } catch {
                guard !Task.isCancelled else { return }
                captionLog.notice("captions: cue fetch failed for \(track.languageCode, privacy: .public): \(String(describing: error), privacy: .public)")
            }
        }
    }

    /// Fetches the track list for `video` once. Audio-only (Music) sessions skip it: there is
    /// nothing to caption. When the remembered language is available it is enabled directly.
    func loadCaptionTracksIfNeeded(for video: Video) {
        guard !isAudioOnlySession, captionTracksVideoID != video.id else { return }
        captionTracksVideoID = video.id
        let remembered = preferences.captionLanguageCode
        Task { [weak self] in
            guard let self else { return }
            let tracks = (try? await self.captionService.tracks(videoID: video.id)) ?? []
            guard self.currentVideo?.id == video.id else { return }
            self.captionTracks = tracks
            if !remembered.isEmpty, self.selectedCaptionTrack == nil,
               let match = tracks.first(where: { $0.languageCode == remembered && !$0.isAutoGenerated })
                ?? tracks.first(where: { $0.languageCode == remembered }) {
                self.selectCaption(match)
            }
        }
    }

    func resetCaptions() {
        captionTask?.cancel()
        captionTask = nil
        captionTracks = []
        selectedCaptionTrack = nil
        captionCues = []
        currentCaptionText = nil
        captionTracksVideoID = nil
    }

    /// Called from the periodic time observer. Cues are sorted by start time, so a binary search
    /// keeps this O(log n) for hour-long transcripts.
    func updateCurrentCaption() {
        guard selectedCaptionTrack != nil, !captionCues.isEmpty else {
            if currentCaptionText != nil { currentCaptionText = nil }
            return
        }
        let time = elapsed
        var low = 0, high = captionCues.count - 1
        var candidate: CaptionCue?
        while low <= high {
            let mid = (low + high) / 2
            let cue = captionCues[mid]
            if cue.start <= time {
                candidate = cue
                low = mid + 1
            } else {
                high = mid - 1
            }
        }
        let text = candidate.flatMap { time < $0.end ? $0.text : nil }
        if text != currentCaptionText { currentCaptionText = text }
    }
}

private let captionLog = AppLog(subsystem: "com.leshko.freetube", category: "PlayerStateManager")
